// Owns: the knowledge base's files — notes, maps, profile files, collections and session summaries
// (PROJECT.md §4.2–§4.6) — and `knowledge/index.md`, the one of them that is generated (§4.4).
// Reading, writing, and the schemas each kind is held to. A collection's item lines are parsed in
// `lib/knowledge/items.ts`, which is pure.
//
// **The index is regenerated by comparing content, never by a flag or a timestamp.** It is rendered
// from the maps, profile files and collections on disk and written only when the text differs from
// what is there. That is what makes a checkout whose index predates this module repair itself the
// first time anything regenerates it — its links were knowledge-relative, and a content comparison
// sees that where a "has anything changed since" flag would not.
//
// Failure behavior: a record whose frontmatter will not parse throws `StoreError("invalid")` from
// every reader here; the callers that scan (`kb:check`, the link index) catch it and report the path.
// The index is a view, so a map it cannot read is listed under its filename rather than dropped.

import { randomBytes } from "node:crypto";
import { z } from "zod";
import { StoreError } from "./paths.ts";
import { joinFrontmatter, splitFrontmatter } from "./frontmatter.ts";
import { exists, listTree, readText, writeText } from "./files.ts";
import { readSettings } from "./settings.ts";
import { nowIso, todayIn } from "../schedule/dates.ts";
import type { TreeNode } from "./files.ts";

export const INDEX_PATH = "knowledge/index.md";

/** §6.1's three, in the order the index and the context assembly both list them. */
export const PROFILE_FILES = [
  "knowledge/profile/about-me.md",
  "knowledge/profile/habits.md",
  "knowledge/profile/preferences.md",
];

/** §6.1: a profile file past this many lines owes a distillation. */
export const PROFILE_CAP = 150;

/** §4.2: a note's body past this many words is reported by `kb:check`, never refused on write. */
export const NOTE_WORD_CAP = 200;

export type KnowledgeKind = "note" | "map" | "profile" | "collection" | "session" | "index";

/** Which of §4's formats a path is held to, from where it sits. Null outside the knowledge base. */
export function kindOf(rel: string): KnowledgeKind | null {
  if (rel === INDEX_PATH) return "index";
  if (!rel.endsWith(".md")) return null;
  if (/^knowledge\/notes\/.+/.test(rel)) return "note";
  if (/^knowledge\/maps\/[^/]+$/.test(rel)) return "map";
  if (/^knowledge\/profile\/[^/]+$/.test(rel)) return "profile";
  if (/^knowledge\/collections\/[^/]+$/.test(rel)) return "collection";
  if (/^knowledge\/sessions\/c_[0-9a-z_]+\.md$/.test(rel)) return "session";
  return null;
}

const stamp = z.string();

export const NoteSchema = z.looseObject({
  schema: z.number().int().default(1),
  id: z.string(),
  title: z.string().min(1),
  type: z.enum(["fact", "how-to", "reference", "decision", "person", "course", "project"]).default("fact"),
  tags: z.array(z.string()).default([]),
  links: z.array(z.string()).default([]),
  source: z.string().default("manual"),
  confidence: z.enum(["low", "medium", "high"]).default("medium"),
  updatedAt: stamp,
});

export const MapSchema = z.looseObject({
  schema: z.number().int().default(1),
  id: z.string(),
  title: z.string().min(1),
  updatedAt: stamp,
});

export const CollectionSchema = z.looseObject({
  schema: z.number().int().default(1),
  id: z.string(),
  title: z.string().min(1),
  kind: z.enum(["list", "reference"]).default("list"),
  context: z.string().nullable().default(null),
  tags: z.array(z.string()).default([]),
  links: z.array(z.string()).default([]),
  tasks: z.array(z.string()).default([]),
  createdAt: stamp,
  updatedAt: stamp,
});

export const SessionSchema = z.looseObject({
  schema: z.number().int().default(1),
  id: z.string(),
  title: z.string().min(1),
  createdAt: stamp,
  messageCount: z.number().int().min(0),
});

/** The field order each kind is written in, matching the examples in §4. Unknown keys follow. */
const ORDER: Record<string, readonly string[]> = {
  note: ["schema", "id", "title", "type", "tags", "links", "source", "confidence", "updatedAt"],
  map: ["schema", "id", "title", "updatedAt"],
  collection: ["schema", "id", "title", "kind", "context", "tags", "links", "tasks", "createdAt", "updatedAt"],
  session: ["schema", "id", "title", "createdAt", "messageCount"],
};

const SCHEMAS = { note: NoteSchema, map: MapSchema, collection: CollectionSchema, session: SessionSchema };

/** Title to slug: lowercase ASCII words joined by hyphens, at most 40 characters, never empty. */
export function slugify(text: string, fallback: string): string {
  const base = text
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (base.length <= 40) return base || fallback;
  const cut = base.slice(0, 40);
  const boundary = cut.lastIndexOf("-");
  return (boundary > 0 ? cut.slice(0, boundary) : cut).replace(/-+$/, "") || fallback;
}

/** The first `# ` heading in `body`, or null. */
export function headingOf(body: string): string | null {
  const match = /^#\s+(.+?)\s*#*\s*$/m.exec(body);
  return match ? match[1].trim() : null;
}

/**
 * A note's title when a proposal did not give one: the frontmatter's, then the first heading, then
 * the filename. Used once, at write time — the result is persisted into frontmatter, so a later edit
 * to the opening line never renames the note behind anyone's back.
 */
export function noteTitleFrom(data: Record<string, unknown>, body: string, rel: string): string {
  if (typeof data.title === "string" && data.title.trim()) return data.title.trim();
  const heading = headingOf(body);
  if (heading) return heading;
  const name = rel.split("/").pop()?.replace(/\.md$/, "") ?? "note";
  const words = name.replace(/[-_]+/g, " ").trim();
  return words ? words[0].toUpperCase() + words.slice(1) : "Untitled note";
}

/** A body with `text` appended on its own lines — the only way anything is added to a file here. */
export function appendLines(body: string, text: string): string {
  const addition = text.replace(/\s+$/, "");
  if (addition.length === 0) return body;
  const base = body.length === 0 || body.endsWith("\n") ? body : `${body}\n`;
  return `${base}${addition}\n`;
}

export async function readRecord(rel: string): Promise<{ data: Record<string, unknown>; body: string }> {
  return splitFrontmatter(await readText(rel));
}

/** Every `.md` file under `knowledge/`, sorted. */
export async function listKnowledge(): Promise<string[]> {
  const found: string[] = [];
  const walk = (nodes: TreeNode[]): void => {
    for (const node of nodes) {
      if (node.type === "dir") walk(node.children ?? []);
      else if (node.path.endsWith(".md")) found.push(node.path);
    }
  };
  walk(await listTree("knowledge"));
  return found.sort();
}

/** `<prefix>_<YYYYMMDD>_<4 hex>` (§4.2, §4.5), regenerated on collision with an id already in use. */
export async function newKnowledgeId(prefix: "n" | "k"): Promise<string> {
  const day = todayIn((await readSettings()).timezone).replace(/-/g, "");
  const taken = new Set<unknown>();
  for (const rel of await listKnowledge()) {
    try {
      taken.add((await readRecord(rel)).data.id);
    } catch {
      // an unreadable file cannot claim an id; kb:check reports it
    }
  }
  for (;;) {
    const id = `${prefix}_${day}_${randomBytes(2).toString("hex")}`;
    if (!taken.has(id)) return id;
  }
}

/**
 * Write a record of `kind` — validated against its schema, `updatedAt` stamped, fields in §4's
 * order — at `rel`. Profile files have no frontmatter and are written as the body alone.
 */
export async function writeRecord(
  rel: string,
  kind: "note" | "map" | "collection" | "session" | "profile",
  data: Record<string, unknown>,
  body: string,
): Promise<void> {
  if (kind === "profile") {
    await writeText(rel, body);
    return;
  }
  const now = nowIso((await readSettings()).timezone);
  const stamped = kind === "session" ? data : { ...data, updatedAt: now };
  const fields = SCHEMAS[kind].parse(kind === "collection" ? { createdAt: now, ...stamped } : stamped);
  const record: Record<string, unknown> = {};
  for (const key of ORDER[kind]) if (key in fields) record[key] = (fields as Record<string, unknown>)[key];
  for (const [key, value] of Object.entries(fields)) if (!(key in record)) record[key] = value;
  await writeText(rel, joinFrontmatter(record, body));
}

/** Title for the index: a map's or collection's frontmatter title, else a heading, else the name. */
async function labelOf(rel: string): Promise<string> {
  try {
    const { data, body } = await readRecord(rel);
    if (typeof data.title === "string" && data.title.trim()) return data.title.trim();
    return headingOf(body) ?? noteTitleFrom({}, "", rel);
  } catch {
    return noteTitleFrom({}, "", rel);
  }
}

/**
 * §4.4's content, exactly: a heading, one link per profile file, one per map with its title, one per
 * collection. Every link is `data/`-relative — the form `read_knowledge` takes — so a model that
 * follows the index reaches the file on its first try.
 */
export async function renderIndex(): Promise<string> {
  const all = await listKnowledge();
  const line = async (rel: string): Promise<string> => `- [${await labelOf(rel)}](${rel})`;
  const byTitle = async (rels: string[]): Promise<string[]> => {
    const rows = await Promise.all(rels.map(async (rel) => ({ rel, title: await labelOf(rel) })));
    return rows.sort((a, b) => a.title.localeCompare(b.title)).map((row) => `- [${row.title}](${row.rel})`);
  };

  const profiles = await Promise.all(PROFILE_FILES.map(line));
  const maps = await byTitle(all.filter((rel) => kindOf(rel) === "map"));
  const collections = await byTitle(all.filter((rel) => kindOf(rel) === "collection"));

  return [
    "# Knowledge",
    "",
    "Generated. Edits here are overwritten; edit the maps instead.",
    "",
    "## Profile",
    "",
    "Always loaded into the assistant's context.",
    "",
    ...profiles,
    "",
    "## Maps",
    "",
    "Hand-curated entry points. A note belongs to at least one map, or `npm run kb:check` calls it an orphan.",
    "",
    ...(maps.length > 0 ? maps : ["None yet."]),
    "",
    "## Collections",
    "",
    ...(collections.length > 0 ? collections : ["None yet."]),
    "",
  ].join("\n");
}

/** Rewrite the index if its content would change. Returns whether it did. */
export async function regenerateIndex(): Promise<boolean> {
  const next = await renderIndex();
  if ((await exists(INDEX_PATH)) && (await readText(INDEX_PATH)) === next) return false;
  await writeText(INDEX_PATH, next);
  return true;
}

/** Refuse a write to a path this module does not recognise as one of §4's knowledge formats. */
export function requireKind(rel: string): KnowledgeKind {
  const kind = kindOf(rel);
  if (kind === null) {
    throw new StoreError("invalid", `${rel} is not a note, map, profile file, collection or session summary`);
  }
  return kind;
}
